### ISSUE TITLE
Build failure :(

### ISSUE THREAD

**Issue by ClaraAllende** [namcent/Quidditch#7]
Hola @ManuelaGomezM @namcent 
Dice maven que no pasan los tests :( 
![image](https://user-images.githubusercontent.com/876039/64898876-43d85900-d65f-11e9-9575-5eee9bdcb7f3.png)

Lo revisan? Así puedo seguir mirando? 
beso!

**Comment by namcent** [comment]
Hola @ClaraAllende 
Ya estaría resuelto el error en el test. 
Besos
